version: 1.3.4.{build}

cache:
- tools -> build.cake

build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: ./artifacts/*.nupkg
  name: Nuget

deploy:
  provider: NuGet
  api_key:
    secure: SAHX7Jn9TZhXK6RWjsvEHxwUnLLB6bJn4TWJHx/wkgZ5SJhictWqrhp2vbChzF4t
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/